version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434" 
    volumes:
      - ollama-moa2:/root/.ollama
    env_file:
      - .env
    pull_policy: always
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile.openweb.ui
      # dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui-moa2:/app/backend/data
      - ./data/litellm/config.yaml:/app/backend/data/litellm/config.yaml
      - ./:/work
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
      # - 14365:14365
    env_file:
      - .env

    # extra_hosts:
    #   - host.docker.internal:host-gateway
    restart: unless-stopped

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    volumes:  
      - ./data/litellm/config.yaml:/app/config.yaml
    ports:
      - "14365:14365"
    command:
      - /bin/sh
      - -c  
      - |
        pip install async_generator
        litellm --config '/app/config.yaml' --debug --host 0.0.0.0 --port 14365 --num_workers 8
    entrypoint: []
    env_file:
      - .env
volumes:
  ollama-moa2: {}
  open-webui-moa2: {}