version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    tty: true