version: '3.8'

services:
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - "9099:9099"
    volumes:
      - pipelines-data:/app/pipelines
    environment:
      - HOST=0.0.0.0
      - PORT=9099
    restart: unless-stopped

  open-webui:
    depends_on:
      - pipelines
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - OPENAI_API_BASE=http://pipelines:9099/v1
      - OPENAI_API_KEY=0p3n-w3bu!

volumes:
  pipelines-data: {}
