ss-mode:
 - DocuMind
# docuMind-model: "gemini/gemini-1.5-pro-latest"
docuMind-model: "gemini/gemini-1.5-flash"
# docuMind-model: "gpt-4o-mini"
docuMind-db: ".SourceSageAssets/DOCUMIND/Repository_summary.md"
docuMind-release-report: ".SourceSageAssets/RELEASE_REPORT/Report_v0.5.3.md"
docuMind-changelog: ".SourceSageAssets/Changelog/CHANGELOG_main.md"
docuMind-output: ".SourceSageAssets/DOCUMIND/RELEASE_NOTES_v0.5.3.md"
docuMind-prompt-output: ".SourceSageAssets/DOCUMIND/_PROMPT_v0.5.3.md"
repo-name: "MOA"
repo-version: "v0.6.1"

# changelog-start-tag: "v0.1.0"
# changelog-end-tag: "v0.5.3"
# sourcesage --ss-mode=DocuMind --yaml-file=docs\.sourcesage_releasenotes.yml
